# -*- coding: utf-8 -*-
"""C118

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GAAf2pyOOCNkTag73wQIVkAne7S8pPM3
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.express as px
df=pd.read_csv("data1.csv")
print(df.head())
fig=px.scatter(df,x="Size",y="Light")
fig.show()

from sklearn.cluster import KMeans
x=df.iloc[:,[0,1]].values
print(x)
wcss=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(x)
  wcss.append(kmeans.inertia_)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,5))
sns.lineplot(range(1,11),wcss,marker='o',color='red')
plt.title('The Elbow method')
plt.xlabel('Number Of Clusters')
plt.ylabel('WCSS')
plt.show()

kmeans=KMeans(n_clusters=3,init='k-means++',random_state=42)
y_kmeans=kmeans.fit_predict(x)

plt.figure(figsize=(15,7))
sns.scatterplot(x[y_kmeans==0,0],x[y_kmeans==0,1],color='yellow')
sns.scatterplot(x[y_kmeans==1,0],x[y_kmeans==1,1],color='blue')
sns.scatterplot(x[y_kmeans==2,0],x[y_kmeans==2,1],color='green')
sns.scatterplot(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],color='red',label='Centroids',s=100,marker=',')
plt.grid(False)
plt.title('Clusters Of Flower')
plt.xlabel('Petal Size')
plt.ylabel('Sepal Size')
plt.legend()
plt.show()